import {
  sub,
  sum,
  mult,
  div,
  clearOperator,
  functionOperator,
  numberOperator,
  equalsOperator,
} from "./operators"

export const inputs = [
  {
    input: "AC",
    row: "1",
    col: "col-span-2",
    operator: clearOperator,
    identifier: "clear",
  },
  {
    input: "/",
    row: "1",
    col: "1",
    operator: functionOperator,
    operation: div,
    identifier: "operator",
  },
  {
    input: "*",
    row: "1",
    col: "1",
    operator: functionOperator,
    operation: mult,
    identifier: "operator",
  },
  {
    input: "7",
    row: "1",
    col: "1",
    operator: numberOperator,
    identifier: "number",
  },
  {
    input: "8",
    row: "1",
    col: "1",
    operator: numberOperator,
    identifier: "number",
  },
  {
    input: "9",
    row: "1",
    col: "1",
    operator: numberOperator,
    identifier: "number",
  },
  {
    input: "-",
    row: "1",
    col: "1",
    operator: functionOperator,
    operation: sub,
    identifier: "operator",
  },
  {
    input: "4",
    row: "1",
    col: "1",
    operator: numberOperator,
    identifier: "number",
  },
  {
    input: "5",
    row: "1",
    col: "1",
    operator: numberOperator,
    identifier: "number",
  },
  {
    input: "6",
    row: "1",
    col: "1",
    operator: numberOperator,
    identifier: "number",
  },
  {
    input: "+",
    row: "1",
    col: "1",
    operator: functionOperator,
    operation: sum,
    identifier: "operator",
  },
  {
    input: "1",
    row: "1",
    col: "1",
    operator: numberOperator,
    identifier: "number",
  },
  {
    input: "2",
    row: "1",
    col: "1",
    operator: numberOperator,
    identifier: "number",
  },
  {
    input: "3",
    row: "1",
    col: "1",
    operator: numberOperator,
    identifier: "number",
  },
  {
    input: "=",
    row: "row-span-2",
    col: "1",
    operator: equalsOperator,
    identifier: "operator",
  },
  {
    input: "0",
    row: "1",
    col: "col-span-2",
    operator: numberOperator,
    identifier: "number",
  },
  {
    input: ".",
    row: "1",
    col: "1",
    operator: numberOperator,
    identifier: "number",
  },
]
